# Generated by Django 5.1.2 on 2024-10-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotyWebApp', '0003_alter_artista_genero_alter_cancion_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
