# Generated by Django 5.1.2 on 2024-11-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotyWebApp', '0005_cancion_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='genero',
            name='origen',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
